### ISSUE TITLE
Some karet.util functions always return observables

### ISSUE THREAD

**Issue by rikutiira** [calmm-js/karet.util#33]
Most functions under `Kefir` section return observables no matter what their input is.

It's especially troublesome for very generic type of functions like `U.when` or `U.ifElse` which are likely to be used extensively throughout your codebase. They are usually better alternatives to `R.when` and `R.ifElse` due to them working with values instead of functions.

I'm doing some optimization for our app, and this has turned out to be one of the biggest peformance issues for us. It's especially problematic for large tables which use generic components like inputs or dropdowns which use the functions grouped under `Kefir`, causing slowness due to thousands or tens of thousands of Kefir subscribers.

Would it be okay to make a PR so that these functions will not return observables unless needed? Conditionals should be quite straightforward but perhaps some combinators need some extra thinking.

**Comment by polytypic** [comment]
Hmm... Does this relate / compare to #28?

**Comment by rikutiira** [comment]
Yeah, the fixes there should be sufficient to fix the issues mentioned above 👍

**Comment by polytypic** [comment]
Released 0.19.0
